create sequence metadata_metadata_id_seq;

alter sequence metadata_metadata_id_seq owner to postgres;

create sequence content_info_content_id_seq;

alter sequence content_info_content_id_seq owner to postgres;

create table file_info
(
    file_id               bigint generated always as identity
        constraint file_info_pk
            primary key,
    parent_directory_path varchar(255) not null,
    file_type             varchar(255) not null,
    file_extension        varchar(25),
    file_name             varchar(255)
);

alter table file_info
    owner to postgres;

create index file_path_index
    on file_info (parent_directory_path, file_name);

create table metadata
(
    file_id            bigint generated by default as identity
        constraint metadata_pk
            primary key,
    file_key           varchar(255),
    regular_file       boolean,
    symbolic_link      boolean,
    other_file         boolean,
    size               bigint,
    creation_time      timestamp,
    last_access_time   timestamp,
    last_modified_time timestamp
);

alter table metadata
    owner to postgres;

alter sequence metadata_metadata_id_seq owned by metadata.file_id;

create table content_info
(
    file_id            bigint generated by default as identity
        constraint content_info_pk
            primary key,
    raw_content        text,
    searchable_content tsvector not null
);

alter table content_info
    owner to postgres;

alter sequence content_info_content_id_seq owned by content_info.file_id;

create index idx_documents_search_vector
    on content_info using gin (searchable_content);

create function documents_tsvector_trigger() returns trigger
    language plpgsql
as
$$
begin
    new.searchable_content := to_tsvector('simple', new.raw_content);
    return new;
end
$$;

alter function documents_tsvector_trigger() owner to postgres;

create trigger tsvectorupdate
    before insert or update
    on content_info
    for each row
execute procedure documents_tsvector_trigger();

