create sequence metadata_metadata_id_seq;

alter sequence metadata_metadata_id_seq owner to postgres;

create sequence content_info_content_id_seq;

alter sequence content_info_content_id_seq owner to postgres;

create sequence metadata_file_id_seq;

alter sequence metadata_file_id_seq owner to postgres;

-- Unknown how to generate base type type

alter type vector owner to postgres;

-- Unknown how to generate base type type

alter type halfvec owner to postgres;

-- Unknown how to generate base type type

alter type sparsevec owner to postgres;

create table file_info
(
    file_id               bigint generated always as identity
        constraint file_info_pk
            primary key,
    parent_directory_path varchar(255) not null,
    file_type             varchar(255) not null,
    file_extension        varchar(25),
    file_name             varchar(255)
);

alter table file_info
    owner to postgres;

create index file_path_index
    on file_info (parent_directory_path, file_name);

create index idx_fileinfo_fileid_path
    on file_info (file_id, parent_directory_path);

create table metadata
(
    file_id            bigint generated by default as identity
        constraint metadata_pk
            primary key
        constraint metadata___fk
            references file_info
            on delete cascade,
    file_key           varchar(255),
    regular_file       boolean,
    symbolic_link      boolean,
    other_file         boolean,
    size               bigint,
    creation_time      timestamp,
    last_modified_time timestamp,
    scan_id            bigint
);

alter table metadata
    owner to postgres;

alter sequence metadata_metadata_id_seq owned by metadata.file_id;

create index scan_id_index
    on metadata (file_id, scan_id);

create table content_info
(
    file_id            bigint generated by default as identity
        constraint content_info_pk
            primary key
        constraint content_info___fk
            references file_info
            on delete cascade,
    raw_content        text,
    searchable_content tsvector not null
);

alter table content_info
    owner to postgres;

create index idx_documents_search_vector
    on content_info using gin (searchable_content);

create table rank_info
(
    file_id            bigint generated by default as identity
        constraint rank_info_pk
            primary key
        constraint rank_info___fk
            references file_info
            on delete cascade,
    file_path          varchar(255) not null,
    depth_path         integer,
    length_path        integer,
    extension_priority integer,
    size               bigint,
    combined_score     double precision,
    last_modified_time timestamp
);

alter table rank_info
    owner to postgres;

create index rank_info_file_path_index
    on rank_info (file_path);

create table search_request_history
(
    id        bigint generated always as identity
        constraint search_request_history_pk
            primary key,
    request   varchar(500) not null,
    timestamp timestamp
);

alter table search_request_history
    owner to postgres;

create index search_request_history_request_index
    on search_request_history (request);

create table search_result_history
(
    id          bigint generated always as identity
        constraint search_result_history_pk
            primary key,
    file_path   varchar(500) not null,
    timestamp   timestamp,
    apparitions integer      not null
);

alter table search_result_history
    owner to postgres;

create unique index search_result_history_file_path_uindex
    on search_result_history (file_path);

create table chunk_info
(
    id        bigint generated always as identity
        constraint chunk_info_pk
            primary key,
    file_path varchar(500) not null,
    embedding vector(384),
    content   text,
    file_id   bigint
        constraint chunk_info___fk
            references file_info
            on delete cascade
);

alter table chunk_info
    owner to postgres;

create index chunk_info_file_id_index
    on chunk_info (file_id);

create index chunk_info_embedding_index
    on chunk_info using hnsw (embedding vector_cosine_ops);

create function documents_tsvector_trigger() returns trigger
    language plpgsql
as
$$
begin
    new.searchable_content := to_tsvector('simple', new.raw_content);
    return new;
end
$$;

alter function documents_tsvector_trigger() owner to postgres;

create trigger tsvectorupdate
    before insert or update
    on content_info
    for each row
execute procedure documents_tsvector_trigger();

create function vector_in(cstring, oid, integer) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_in(cstring, oid, integer) owner to postgres;

create function vector_out(vector) returns cstring
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_out(vector) owner to postgres;

create function vector_typmod_in(cstring[]) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_typmod_in(cstring[]) owner to postgres;

create function vector_recv(internal, oid, integer) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_recv(internal, oid, integer) owner to postgres;

create function vector_send(vector) returns bytea
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_send(vector) owner to postgres;

create function l2_distance(vector, vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function l2_distance(vector, vector) owner to postgres;

create function inner_product(vector, vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function inner_product(vector, vector) owner to postgres;

create function cosine_distance(vector, vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function cosine_distance(vector, vector) owner to postgres;

create function l1_distance(vector, vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function l1_distance(vector, vector) owner to postgres;

create function vector_dims(vector) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_dims(vector) owner to postgres;

create function vector_norm(vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_norm(vector) owner to postgres;

create function l2_normalize(vector) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function l2_normalize(vector) owner to postgres;

create function binary_quantize(vector) returns bit
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function binary_quantize(vector) owner to postgres;

create function subvector(vector, integer, integer) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function subvector(vector, integer, integer) owner to postgres;

create function vector_add(vector, vector) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_add(vector, vector) owner to postgres;

create function vector_sub(vector, vector) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_sub(vector, vector) owner to postgres;

create function vector_mul(vector, vector) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_mul(vector, vector) owner to postgres;

create function vector_concat(vector, vector) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_concat(vector, vector) owner to postgres;

create function vector_lt(vector, vector) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_lt(vector, vector) owner to postgres;

create function vector_le(vector, vector) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_le(vector, vector) owner to postgres;

create function vector_eq(vector, vector) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_eq(vector, vector) owner to postgres;

create function vector_ne(vector, vector) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_ne(vector, vector) owner to postgres;

create function vector_ge(vector, vector) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_ge(vector, vector) owner to postgres;

create function vector_gt(vector, vector) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_gt(vector, vector) owner to postgres;

create function vector_cmp(vector, vector) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_cmp(vector, vector) owner to postgres;

create function vector_l2_squared_distance(vector, vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_l2_squared_distance(vector, vector) owner to postgres;

create function vector_negative_inner_product(vector, vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_negative_inner_product(vector, vector) owner to postgres;

create function vector_spherical_distance(vector, vector) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_spherical_distance(vector, vector) owner to postgres;

create function vector_accum(double precision[], vector) returns double precision[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_accum(double precision[], vector) owner to postgres;

create function vector_avg(double precision[]) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_avg(double precision[]) owner to postgres;

create function vector_combine(double precision[], double precision[]) returns double precision[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_combine(double precision[], double precision[]) owner to postgres;

create function vector(vector, integer, boolean) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector(vector, integer, boolean) owner to postgres;

create function array_to_vector(integer[], integer, boolean) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function array_to_vector(integer[], integer, boolean) owner to postgres;

create function array_to_vector(real[], integer, boolean) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function array_to_vector(real[], integer, boolean) owner to postgres;

create function array_to_vector(double precision[], integer, boolean) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function array_to_vector(double precision[], integer, boolean) owner to postgres;

create function array_to_vector(numeric[], integer, boolean) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function array_to_vector(numeric[], integer, boolean) owner to postgres;

create function vector_to_float4(vector, integer, boolean) returns real[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_to_float4(vector, integer, boolean) owner to postgres;

create function ivfflathandler(internal) returns index_am_handler
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function ivfflathandler(internal) owner to postgres;

create function hnswhandler(internal) returns index_am_handler
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function hnswhandler(internal) owner to postgres;

create function ivfflat_halfvec_support(internal) returns internal
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function ivfflat_halfvec_support(internal) owner to postgres;

create function ivfflat_bit_support(internal) returns internal
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function ivfflat_bit_support(internal) owner to postgres;

create function hnsw_halfvec_support(internal) returns internal
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function hnsw_halfvec_support(internal) owner to postgres;

create function hnsw_bit_support(internal) returns internal
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function hnsw_bit_support(internal) owner to postgres;

create function hnsw_sparsevec_support(internal) returns internal
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function hnsw_sparsevec_support(internal) owner to postgres;

create function halfvec_in(cstring, oid, integer) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_in(cstring, oid, integer) owner to postgres;

create function halfvec_out(halfvec) returns cstring
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_out(halfvec) owner to postgres;

create function halfvec_typmod_in(cstring[]) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_typmod_in(cstring[]) owner to postgres;

create function halfvec_recv(internal, oid, integer) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_recv(internal, oid, integer) owner to postgres;

create function halfvec_send(halfvec) returns bytea
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_send(halfvec) owner to postgres;

create function l2_distance(halfvec, halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function l2_distance(halfvec, halfvec) owner to postgres;

create function inner_product(halfvec, halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function inner_product(halfvec, halfvec) owner to postgres;

create function cosine_distance(halfvec, halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function cosine_distance(halfvec, halfvec) owner to postgres;

create function l1_distance(halfvec, halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function l1_distance(halfvec, halfvec) owner to postgres;

create function vector_dims(halfvec) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_dims(halfvec) owner to postgres;

create function l2_norm(halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function l2_norm(halfvec) owner to postgres;

create function l2_normalize(halfvec) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function l2_normalize(halfvec) owner to postgres;

create function binary_quantize(halfvec) returns bit
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function binary_quantize(halfvec) owner to postgres;

create function subvector(halfvec, integer, integer) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function subvector(halfvec, integer, integer) owner to postgres;

create function halfvec_add(halfvec, halfvec) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_add(halfvec, halfvec) owner to postgres;

create function halfvec_sub(halfvec, halfvec) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_sub(halfvec, halfvec) owner to postgres;

create function halfvec_mul(halfvec, halfvec) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_mul(halfvec, halfvec) owner to postgres;

create function halfvec_concat(halfvec, halfvec) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_concat(halfvec, halfvec) owner to postgres;

create function halfvec_lt(halfvec, halfvec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_lt(halfvec, halfvec) owner to postgres;

create function halfvec_le(halfvec, halfvec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_le(halfvec, halfvec) owner to postgres;

create function halfvec_eq(halfvec, halfvec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_eq(halfvec, halfvec) owner to postgres;

create function halfvec_ne(halfvec, halfvec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_ne(halfvec, halfvec) owner to postgres;

create function halfvec_ge(halfvec, halfvec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_ge(halfvec, halfvec) owner to postgres;

create function halfvec_gt(halfvec, halfvec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_gt(halfvec, halfvec) owner to postgres;

create function halfvec_cmp(halfvec, halfvec) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_cmp(halfvec, halfvec) owner to postgres;

create function halfvec_l2_squared_distance(halfvec, halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_l2_squared_distance(halfvec, halfvec) owner to postgres;

create function halfvec_negative_inner_product(halfvec, halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_negative_inner_product(halfvec, halfvec) owner to postgres;

create function halfvec_spherical_distance(halfvec, halfvec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_spherical_distance(halfvec, halfvec) owner to postgres;

create function halfvec_accum(double precision[], halfvec) returns double precision[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_accum(double precision[], halfvec) owner to postgres;

create function halfvec_avg(double precision[]) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_avg(double precision[]) owner to postgres;

create function halfvec_combine(double precision[], double precision[]) returns double precision[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_combine(double precision[], double precision[]) owner to postgres;

create function halfvec(halfvec, integer, boolean) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec(halfvec, integer, boolean) owner to postgres;

create function halfvec_to_vector(halfvec, integer, boolean) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_to_vector(halfvec, integer, boolean) owner to postgres;

create function vector_to_halfvec(vector, integer, boolean) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_to_halfvec(vector, integer, boolean) owner to postgres;

create function array_to_halfvec(integer[], integer, boolean) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function array_to_halfvec(integer[], integer, boolean) owner to postgres;

create function array_to_halfvec(real[], integer, boolean) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function array_to_halfvec(real[], integer, boolean) owner to postgres;

create function array_to_halfvec(double precision[], integer, boolean) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function array_to_halfvec(double precision[], integer, boolean) owner to postgres;

create function array_to_halfvec(numeric[], integer, boolean) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function array_to_halfvec(numeric[], integer, boolean) owner to postgres;

create function halfvec_to_float4(halfvec, integer, boolean) returns real[]
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_to_float4(halfvec, integer, boolean) owner to postgres;

create function hamming_distance(bit, bit) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function hamming_distance(bit, bit) owner to postgres;

create function jaccard_distance(bit, bit) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function jaccard_distance(bit, bit) owner to postgres;

create function sparsevec_in(cstring, oid, integer) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_in(cstring, oid, integer) owner to postgres;

create function sparsevec_out(sparsevec) returns cstring
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_out(sparsevec) owner to postgres;

create function sparsevec_typmod_in(cstring[]) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_typmod_in(cstring[]) owner to postgres;

create function sparsevec_recv(internal, oid, integer) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_recv(internal, oid, integer) owner to postgres;

create function sparsevec_send(sparsevec) returns bytea
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_send(sparsevec) owner to postgres;

create function l2_distance(sparsevec, sparsevec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function l2_distance(sparsevec, sparsevec) owner to postgres;

create function inner_product(sparsevec, sparsevec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function inner_product(sparsevec, sparsevec) owner to postgres;

create function cosine_distance(sparsevec, sparsevec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function cosine_distance(sparsevec, sparsevec) owner to postgres;

create function l1_distance(sparsevec, sparsevec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function l1_distance(sparsevec, sparsevec) owner to postgres;

create function l2_norm(sparsevec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function l2_norm(sparsevec) owner to postgres;

create function l2_normalize(sparsevec) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function l2_normalize(sparsevec) owner to postgres;

create function sparsevec_lt(sparsevec, sparsevec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_lt(sparsevec, sparsevec) owner to postgres;

create function sparsevec_le(sparsevec, sparsevec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_le(sparsevec, sparsevec) owner to postgres;

create function sparsevec_eq(sparsevec, sparsevec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_eq(sparsevec, sparsevec) owner to postgres;

create function sparsevec_ne(sparsevec, sparsevec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_ne(sparsevec, sparsevec) owner to postgres;

create function sparsevec_ge(sparsevec, sparsevec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_ge(sparsevec, sparsevec) owner to postgres;

create function sparsevec_gt(sparsevec, sparsevec) returns boolean
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_gt(sparsevec, sparsevec) owner to postgres;

create function sparsevec_cmp(sparsevec, sparsevec) returns integer
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_cmp(sparsevec, sparsevec) owner to postgres;

create function sparsevec_l2_squared_distance(sparsevec, sparsevec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_l2_squared_distance(sparsevec, sparsevec) owner to postgres;

create function sparsevec_negative_inner_product(sparsevec, sparsevec) returns double precision
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_negative_inner_product(sparsevec, sparsevec) owner to postgres;

create function sparsevec(sparsevec, integer, boolean) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec(sparsevec, integer, boolean) owner to postgres;

create function vector_to_sparsevec(vector, integer, boolean) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function vector_to_sparsevec(vector, integer, boolean) owner to postgres;

create function sparsevec_to_vector(sparsevec, integer, boolean) returns vector
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_to_vector(sparsevec, integer, boolean) owner to postgres;

create function halfvec_to_sparsevec(halfvec, integer, boolean) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function halfvec_to_sparsevec(halfvec, integer, boolean) owner to postgres;

create function sparsevec_to_halfvec(sparsevec, integer, boolean) returns halfvec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function sparsevec_to_halfvec(sparsevec, integer, boolean) owner to postgres;

create function array_to_sparsevec(integer[], integer, boolean) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function array_to_sparsevec(integer[], integer, boolean) owner to postgres;

create function array_to_sparsevec(real[], integer, boolean) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function array_to_sparsevec(real[], integer, boolean) owner to postgres;

create function array_to_sparsevec(double precision[], integer, boolean) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function array_to_sparsevec(double precision[], integer, boolean) owner to postgres;

create function array_to_sparsevec(numeric[], integer, boolean) returns sparsevec
    immutable
    strict
    parallel safe
    language c
as
$$
begin
-- missing source code
end;
$$;

alter function array_to_sparsevec(numeric[], integer, boolean) owner to postgres;

create operator <-> (procedure = l2_distance, leftarg = vector, rightarg = vector, commutator = <->);

alter operator <->(vector, vector) owner to postgres;

create operator <#> (procedure = vector_negative_inner_product, leftarg = vector, rightarg = vector, commutator = <#>);

alter operator <#>(vector, vector) owner to postgres;

create operator <=> (procedure = cosine_distance, leftarg = vector, rightarg = vector, commutator = <=>);

alter operator <=>(vector, vector) owner to postgres;

create operator <+> (procedure = l1_distance, leftarg = vector, rightarg = vector, commutator = <+>);

alter operator <+>(vector, vector) owner to postgres;

create operator + (procedure = vector_add, leftarg = vector, rightarg = vector, commutator = +);

alter operator +(vector, vector) owner to postgres;

create operator - (procedure = vector_sub, leftarg = vector, rightarg = vector);

alter operator -(vector, vector) owner to postgres;

create operator * (procedure = vector_mul, leftarg = vector, rightarg = vector, commutator = *);

alter operator *(vector, vector) owner to postgres;

create operator || (procedure = vector_concat, leftarg = vector, rightarg = vector);

alter operator ||(vector, vector) owner to postgres;

create operator <-> (procedure = l2_distance, leftarg = halfvec, rightarg = halfvec, commutator = <->);

alter operator <->(halfvec, halfvec) owner to postgres;

create operator <#> (procedure = halfvec_negative_inner_product, leftarg = halfvec, rightarg = halfvec, commutator = <#>);

alter operator <#>(halfvec, halfvec) owner to postgres;

create operator <=> (procedure = cosine_distance, leftarg = halfvec, rightarg = halfvec, commutator = <=>);

alter operator <=>(halfvec, halfvec) owner to postgres;

create operator <+> (procedure = l1_distance, leftarg = halfvec, rightarg = halfvec, commutator = <+>);

alter operator <+>(halfvec, halfvec) owner to postgres;

create operator + (procedure = halfvec_add, leftarg = halfvec, rightarg = halfvec, commutator = +);

alter operator +(halfvec, halfvec) owner to postgres;

create operator - (procedure = halfvec_sub, leftarg = halfvec, rightarg = halfvec);

alter operator -(halfvec, halfvec) owner to postgres;

create operator * (procedure = halfvec_mul, leftarg = halfvec, rightarg = halfvec, commutator = *);

alter operator *(halfvec, halfvec) owner to postgres;

create operator || (procedure = halfvec_concat, leftarg = halfvec, rightarg = halfvec);

alter operator ||(halfvec, halfvec) owner to postgres;

create operator <~> (procedure = hamming_distance, leftarg = bit, rightarg = bit, commutator = <~>);

alter operator <~>(bit, bit) owner to postgres;

create operator <%> (procedure = jaccard_distance, leftarg = bit, rightarg = bit, commutator = <%>);

alter operator <%>(bit, bit) owner to postgres;

create operator <-> (procedure = l2_distance, leftarg = sparsevec, rightarg = sparsevec, commutator = <->);

alter operator <->(sparsevec, sparsevec) owner to postgres;

create operator <#> (procedure = sparsevec_negative_inner_product, leftarg = sparsevec, rightarg = sparsevec, commutator = <#>);

alter operator <#>(sparsevec, sparsevec) owner to postgres;

create operator <=> (procedure = cosine_distance, leftarg = sparsevec, rightarg = sparsevec, commutator = <=>);

alter operator <=>(sparsevec, sparsevec) owner to postgres;

create operator <+> (procedure = l1_distance, leftarg = sparsevec, rightarg = sparsevec, commutator = <+>);

alter operator <+>(sparsevec, sparsevec) owner to postgres;

create aggregate avg(vector) (
    sfunc = vector_accum,
    stype = double precision[],
    finalfunc = vector_avg,
    combinefunc = vector_combine,
    initcond = '{0}',
    parallel = safe
    );

alter aggregate avg(vector) owner to postgres;

create aggregate sum(vector) (
    sfunc = vector_add,
    stype = vector,
    combinefunc = vector_add,
    parallel = safe
    );

alter aggregate sum(vector) owner to postgres;

create aggregate avg(halfvec) (
    sfunc = halfvec_accum,
    stype = double precision[],
    finalfunc = halfvec_avg,
    combinefunc = halfvec_combine,
    initcond = '{0}',
    parallel = safe
    );

alter aggregate avg(halfvec) owner to postgres;

create aggregate sum(halfvec) (
    sfunc = halfvec_add,
    stype = halfvec,
    combinefunc = halfvec_add,
    parallel = safe
    );

alter aggregate sum(halfvec) owner to postgres;

create operator family vector_ops using btree;

alter operator family vector_ops using btree add
    operator 4 >=(vector, vector),
    operator 1 <(vector, vector),
    operator 2 <=(vector, vector),
    operator 3 =(vector, vector),
    operator 5 >(vector, vector),
    function 1(vector, vector) vector_cmp(vector, vector);

alter operator family vector_ops using btree owner to postgres;

create operator class vector_ops default for type vector using btree as
    operator 3 =(vector, vector),
    operator 1 <(vector, vector),
    operator 5 >(vector, vector),
    operator 2 <=(vector, vector),
    operator 4 >=(vector, vector),
    function 1(vector, vector) vector_cmp(vector, vector);

alter operator class vector_ops using btree owner to postgres;

create operator family vector_l2_ops using ivfflat;

alter operator family vector_l2_ops using ivfflat add
    operator 1 <->(vector, vector) for order by float_ops,
    function 3(vector, vector) l2_distance(vector, vector),
    function 1(vector, vector) vector_l2_squared_distance(vector, vector);

alter operator family vector_l2_ops using ivfflat owner to postgres;

create operator class vector_l2_ops default for type vector using ivfflat as
    operator 1 <->(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_l2_squared_distance(vector, vector),
    function 3(vector, vector) l2_distance(vector, vector);

alter operator class vector_l2_ops using ivfflat owner to postgres;

create operator family vector_ip_ops using ivfflat;

alter operator family vector_ip_ops using ivfflat add
    operator 1 <#>(vector, vector) for order by float_ops,
    function 4(vector, vector) vector_norm(vector),
    function 3(vector, vector) vector_spherical_distance(vector, vector),
    function 1(vector, vector) vector_negative_inner_product(vector, vector);

alter operator family vector_ip_ops using ivfflat owner to postgres;

create operator class vector_ip_ops for type vector using ivfflat as
    operator 1 <#>(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_negative_inner_product(vector, vector),
    function 4(vector, vector) vector_norm(vector),
    function 3(vector, vector) vector_spherical_distance(vector, vector);

alter operator class vector_ip_ops using ivfflat owner to postgres;

create operator family vector_cosine_ops using ivfflat;

alter operator family vector_cosine_ops using ivfflat add
    operator 1 <=>(vector, vector) for order by float_ops,
    function 2(vector, vector) vector_norm(vector),
    function 1(vector, vector) vector_negative_inner_product(vector, vector),
    function 3(vector, vector) vector_spherical_distance(vector, vector),
    function 4(vector, vector) vector_norm(vector);

alter operator family vector_cosine_ops using ivfflat owner to postgres;

create operator class vector_cosine_ops for type vector using ivfflat as
    operator 1 <=>(vector, vector) for order by float_ops,
    function 3(vector, vector) vector_spherical_distance(vector, vector),
    function 4(vector, vector) vector_norm(vector),
    function 1(vector, vector) vector_negative_inner_product(vector, vector),
    function 2(vector, vector) vector_norm(vector);

alter operator class vector_cosine_ops using ivfflat owner to postgres;

create operator family vector_l2_ops using hnsw;

alter operator family vector_l2_ops using hnsw add
    operator 1 <->(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_l2_squared_distance(vector, vector);

alter operator family vector_l2_ops using hnsw owner to postgres;

create operator class vector_l2_ops for type vector using hnsw as
    operator 1 <->(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_l2_squared_distance(vector, vector);

alter operator class vector_l2_ops using hnsw owner to postgres;

create operator family vector_ip_ops using hnsw;

alter operator family vector_ip_ops using hnsw add
    operator 1 <#>(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_negative_inner_product(vector, vector);

alter operator family vector_ip_ops using hnsw owner to postgres;

create operator class vector_ip_ops for type vector using hnsw as
    operator 1 <#>(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_negative_inner_product(vector, vector);

alter operator class vector_ip_ops using hnsw owner to postgres;

create operator family vector_cosine_ops using hnsw;

alter operator family vector_cosine_ops using hnsw add
    operator 1 <=>(vector, vector) for order by float_ops,
    function 1(vector, vector) vector_negative_inner_product(vector, vector),
    function 2(vector, vector) vector_norm(vector);

alter operator family vector_cosine_ops using hnsw owner to postgres;

create operator class vector_cosine_ops for type vector using hnsw as
    operator 1 <=>(vector, vector) for order by float_ops,
    function 2(vector, vector) vector_norm(vector),
    function 1(vector, vector) vector_negative_inner_product(vector, vector);

alter operator class vector_cosine_ops using hnsw owner to postgres;

create operator family vector_l1_ops using hnsw;

alter operator family vector_l1_ops using hnsw add
    operator 1 <+>(vector, vector) for order by float_ops,
    function 1(vector, vector) l1_distance(vector, vector);

alter operator family vector_l1_ops using hnsw owner to postgres;

create operator class vector_l1_ops for type vector using hnsw as
    operator 1 <+>(vector, vector) for order by float_ops,
    function 1(vector, vector) l1_distance(vector, vector);

alter operator class vector_l1_ops using hnsw owner to postgres;

create operator family halfvec_ops using btree;

alter operator family halfvec_ops using btree add
    operator 3 =(halfvec, halfvec),
    operator 4 >=(halfvec, halfvec),
    operator 5 >(halfvec, halfvec),
    operator 2 <=(halfvec, halfvec),
    operator 1 <(halfvec, halfvec),
    function 1(halfvec, halfvec) halfvec_cmp(halfvec, halfvec);

alter operator family halfvec_ops using btree owner to postgres;

create operator class halfvec_ops default for type halfvec using btree as
    operator 1 <(halfvec, halfvec),
    operator 4 >=(halfvec, halfvec),
    operator 5 >(halfvec, halfvec),
    operator 3 =(halfvec, halfvec),
    operator 2 <=(halfvec, halfvec),
    function 1(halfvec, halfvec) halfvec_cmp(halfvec, halfvec);

alter operator class halfvec_ops using btree owner to postgres;

create operator family halfvec_l2_ops using ivfflat;

alter operator family halfvec_l2_ops using ivfflat add
    operator 1 <->(halfvec, halfvec) for order by float_ops,
    function 5(halfvec, halfvec) ivfflat_halfvec_support(internal),
    function 3(halfvec, halfvec) l2_distance(halfvec, halfvec),
    function 1(halfvec, halfvec) halfvec_l2_squared_distance(halfvec, halfvec);

alter operator family halfvec_l2_ops using ivfflat owner to postgres;

create operator class halfvec_l2_ops for type halfvec using ivfflat as
    operator 1 <->(halfvec, halfvec) for order by float_ops,
    function 5(halfvec, halfvec) ivfflat_halfvec_support(internal),
    function 1(halfvec, halfvec) halfvec_l2_squared_distance(halfvec, halfvec),
    function 3(halfvec, halfvec) l2_distance(halfvec, halfvec);

alter operator class halfvec_l2_ops using ivfflat owner to postgres;

create operator family halfvec_ip_ops using ivfflat;

alter operator family halfvec_ip_ops using ivfflat add
    operator 1 <#>(halfvec, halfvec) for order by float_ops,
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec),
    function 3(halfvec, halfvec) halfvec_spherical_distance(halfvec, halfvec),
    function 4(halfvec, halfvec) l2_norm(halfvec),
    function 5(halfvec, halfvec) ivfflat_halfvec_support(internal);

alter operator family halfvec_ip_ops using ivfflat owner to postgres;

create operator class halfvec_ip_ops for type halfvec using ivfflat as
    operator 1 <#>(halfvec, halfvec) for order by float_ops,
    function 4(halfvec, halfvec) l2_norm(halfvec),
    function 3(halfvec, halfvec) halfvec_spherical_distance(halfvec, halfvec),
    function 5(halfvec, halfvec) ivfflat_halfvec_support(internal),
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec);

alter operator class halfvec_ip_ops using ivfflat owner to postgres;

create operator family halfvec_cosine_ops using ivfflat;

alter operator family halfvec_cosine_ops using ivfflat add
    operator 1 <=>(halfvec, halfvec) for order by float_ops,
    function 5(halfvec, halfvec) ivfflat_halfvec_support(internal),
    function 3(halfvec, halfvec) halfvec_spherical_distance(halfvec, halfvec),
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec),
    function 4(halfvec, halfvec) l2_norm(halfvec),
    function 2(halfvec, halfvec) l2_norm(halfvec);

alter operator family halfvec_cosine_ops using ivfflat owner to postgres;

create operator class halfvec_cosine_ops for type halfvec using ivfflat as
    operator 1 <=>(halfvec, halfvec) for order by float_ops,
    function 5(halfvec, halfvec) ivfflat_halfvec_support(internal),
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec),
    function 3(halfvec, halfvec) halfvec_spherical_distance(halfvec, halfvec),
    function 4(halfvec, halfvec) l2_norm(halfvec),
    function 2(halfvec, halfvec) l2_norm(halfvec);

alter operator class halfvec_cosine_ops using ivfflat owner to postgres;

create operator family halfvec_l2_ops using hnsw;

alter operator family halfvec_l2_ops using hnsw add
    operator 1 <->(halfvec, halfvec) for order by float_ops,
    function 1(halfvec, halfvec) halfvec_l2_squared_distance(halfvec, halfvec),
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal);

alter operator family halfvec_l2_ops using hnsw owner to postgres;

create operator class halfvec_l2_ops for type halfvec using hnsw as
    operator 1 <->(halfvec, halfvec) for order by float_ops,
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal),
    function 1(halfvec, halfvec) halfvec_l2_squared_distance(halfvec, halfvec);

alter operator class halfvec_l2_ops using hnsw owner to postgres;

create operator family halfvec_ip_ops using hnsw;

alter operator family halfvec_ip_ops using hnsw add
    operator 1 <#>(halfvec, halfvec) for order by float_ops,
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec),
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal);

alter operator family halfvec_ip_ops using hnsw owner to postgres;

create operator class halfvec_ip_ops for type halfvec using hnsw as
    operator 1 <#>(halfvec, halfvec) for order by float_ops,
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec),
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal);

alter operator class halfvec_ip_ops using hnsw owner to postgres;

create operator family halfvec_cosine_ops using hnsw;

alter operator family halfvec_cosine_ops using hnsw add
    operator 1 <=>(halfvec, halfvec) for order by float_ops,
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec),
    function 2(halfvec, halfvec) l2_norm(halfvec),
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal);

alter operator family halfvec_cosine_ops using hnsw owner to postgres;

create operator class halfvec_cosine_ops for type halfvec using hnsw as
    operator 1 <=>(halfvec, halfvec) for order by float_ops,
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal),
    function 1(halfvec, halfvec) halfvec_negative_inner_product(halfvec, halfvec),
    function 2(halfvec, halfvec) l2_norm(halfvec);

alter operator class halfvec_cosine_ops using hnsw owner to postgres;

create operator family halfvec_l1_ops using hnsw;

alter operator family halfvec_l1_ops using hnsw add
    operator 1 <+>(halfvec, halfvec) for order by float_ops,
    function 1(halfvec, halfvec) l1_distance(halfvec, halfvec),
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal);

alter operator family halfvec_l1_ops using hnsw owner to postgres;

create operator class halfvec_l1_ops for type halfvec using hnsw as
    operator 1 <+>(halfvec, halfvec) for order by float_ops,
    function 3(halfvec, halfvec) hnsw_halfvec_support(internal),
    function 1(halfvec, halfvec) l1_distance(halfvec, halfvec);

alter operator class halfvec_l1_ops using hnsw owner to postgres;

create operator family bit_hamming_ops using ivfflat;

alter operator family bit_hamming_ops using ivfflat add
    operator 1 <~>(bit, bit) for order by float_ops,
    function 3(bit, bit) hamming_distance(bit, bit),
    function 1(bit, bit) hamming_distance(bit, bit),
    function 5(bit, bit) ivfflat_bit_support(internal);

alter operator family bit_hamming_ops using ivfflat owner to postgres;

create operator class bit_hamming_ops for type bit using ivfflat as
    operator 1 <~>(bit, bit) for order by float_ops,
    function 3(bit, bit) hamming_distance(bit, bit),
    function 1(bit, bit) hamming_distance(bit, bit),
    function 5(bit, bit) ivfflat_bit_support(internal);

alter operator class bit_hamming_ops using ivfflat owner to postgres;

create operator family bit_hamming_ops using hnsw;

alter operator family bit_hamming_ops using hnsw add
    operator 1 <~>(bit, bit) for order by float_ops,
    function 1(bit, bit) hamming_distance(bit, bit),
    function 3(bit, bit) hnsw_bit_support(internal);

alter operator family bit_hamming_ops using hnsw owner to postgres;

create operator class bit_hamming_ops for type bit using hnsw as
    operator 1 <~>(bit, bit) for order by float_ops,
    function 1(bit, bit) hamming_distance(bit, bit),
    function 3(bit, bit) hnsw_bit_support(internal);

alter operator class bit_hamming_ops using hnsw owner to postgres;

create operator family bit_jaccard_ops using hnsw;

alter operator family bit_jaccard_ops using hnsw add
    operator 1 <%>(bit, bit) for order by float_ops,
    function 1(bit, bit) jaccard_distance(bit, bit),
    function 3(bit, bit) hnsw_bit_support(internal);

alter operator family bit_jaccard_ops using hnsw owner to postgres;

create operator class bit_jaccard_ops for type bit using hnsw as
    operator 1 <%>(bit, bit) for order by float_ops,
    function 1(bit, bit) jaccard_distance(bit, bit),
    function 3(bit, bit) hnsw_bit_support(internal);

alter operator class bit_jaccard_ops using hnsw owner to postgres;

create operator family sparsevec_ops using btree;

alter operator family sparsevec_ops using btree add
    operator 4 >=(sparsevec, sparsevec),
    operator 5 >(sparsevec, sparsevec),
    operator 1 <(sparsevec, sparsevec),
    operator 3 =(sparsevec, sparsevec),
    operator 2 <=(sparsevec, sparsevec),
    function 1(sparsevec, sparsevec) sparsevec_cmp(sparsevec, sparsevec);

alter operator family sparsevec_ops using btree owner to postgres;

create operator class sparsevec_ops default for type sparsevec using btree as
    operator 3 =(sparsevec, sparsevec),
    operator 4 >=(sparsevec, sparsevec),
    operator 5 >(sparsevec, sparsevec),
    operator 2 <=(sparsevec, sparsevec),
    operator 1 <(sparsevec, sparsevec),
    function 1(sparsevec, sparsevec) sparsevec_cmp(sparsevec, sparsevec);

alter operator class sparsevec_ops using btree owner to postgres;

create operator family sparsevec_l2_ops using hnsw;

alter operator family sparsevec_l2_ops using hnsw add
    operator 1 <->(sparsevec, sparsevec) for order by float_ops,
    function 1(sparsevec, sparsevec) sparsevec_l2_squared_distance(sparsevec, sparsevec),
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal);

alter operator family sparsevec_l2_ops using hnsw owner to postgres;

create operator class sparsevec_l2_ops for type sparsevec using hnsw as
    operator 1 <->(sparsevec, sparsevec) for order by float_ops,
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal),
    function 1(sparsevec, sparsevec) sparsevec_l2_squared_distance(sparsevec, sparsevec);

alter operator class sparsevec_l2_ops using hnsw owner to postgres;

create operator family sparsevec_ip_ops using hnsw;

alter operator family sparsevec_ip_ops using hnsw add
    operator 1 <#>(sparsevec, sparsevec) for order by float_ops,
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal),
    function 1(sparsevec, sparsevec) sparsevec_negative_inner_product(sparsevec, sparsevec);

alter operator family sparsevec_ip_ops using hnsw owner to postgres;

create operator class sparsevec_ip_ops for type sparsevec using hnsw as
    operator 1 <#>(sparsevec, sparsevec) for order by float_ops,
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal),
    function 1(sparsevec, sparsevec) sparsevec_negative_inner_product(sparsevec, sparsevec);

alter operator class sparsevec_ip_ops using hnsw owner to postgres;

create operator family sparsevec_cosine_ops using hnsw;

alter operator family sparsevec_cosine_ops using hnsw add
    operator 1 <=>(sparsevec, sparsevec) for order by float_ops,
    function 2(sparsevec, sparsevec) l2_norm(sparsevec),
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal),
    function 1(sparsevec, sparsevec) sparsevec_negative_inner_product(sparsevec, sparsevec);

alter operator family sparsevec_cosine_ops using hnsw owner to postgres;

create operator class sparsevec_cosine_ops for type sparsevec using hnsw as
    operator 1 <=>(sparsevec, sparsevec) for order by float_ops,
    function 1(sparsevec, sparsevec) sparsevec_negative_inner_product(sparsevec, sparsevec),
    function 2(sparsevec, sparsevec) l2_norm(sparsevec),
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal);

alter operator class sparsevec_cosine_ops using hnsw owner to postgres;

create operator family sparsevec_l1_ops using hnsw;

alter operator family sparsevec_l1_ops using hnsw add
    operator 1 <+>(sparsevec, sparsevec) for order by float_ops,
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal),
    function 1(sparsevec, sparsevec) l1_distance(sparsevec, sparsevec);

alter operator family sparsevec_l1_ops using hnsw owner to postgres;

create operator class sparsevec_l1_ops for type sparsevec using hnsw as
    operator 1 <+>(sparsevec, sparsevec) for order by float_ops,
    function 3(sparsevec, sparsevec) hnsw_sparsevec_support(internal),
    function 1(sparsevec, sparsevec) l1_distance(sparsevec, sparsevec);

alter operator class sparsevec_l1_ops using hnsw owner to postgres;

-- Cyclic dependencies found

create operator <> (procedure = halfvec_ne, leftarg = halfvec, rightarg = halfvec, commutator = <>, negator = =, join = eqjoinsel, restrict = eqsel);

alter operator <>(halfvec, halfvec) owner to postgres;

create operator = (procedure = halfvec_eq, leftarg = halfvec, rightarg = halfvec, commutator = =, negator = <>, join = eqjoinsel, restrict = eqsel);

alter operator =(halfvec, halfvec) owner to postgres;

-- Cyclic dependencies found

create operator <> (procedure = sparsevec_ne, leftarg = sparsevec, rightarg = sparsevec, commutator = <>, negator = =, join = eqjoinsel, restrict = eqsel);

alter operator <>(sparsevec, sparsevec) owner to postgres;

create operator = (procedure = sparsevec_eq, leftarg = sparsevec, rightarg = sparsevec, commutator = =, negator = <>, join = eqjoinsel, restrict = eqsel);

alter operator =(sparsevec, sparsevec) owner to postgres;

-- Cyclic dependencies found

create operator <> (procedure = vector_ne, leftarg = vector, rightarg = vector, commutator = <>, negator = =, join = eqjoinsel, restrict = eqsel);

alter operator <>(vector, vector) owner to postgres;

create operator = (procedure = vector_eq, leftarg = vector, rightarg = vector, commutator = =, negator = <>, join = eqjoinsel, restrict = eqsel);

alter operator =(vector, vector) owner to postgres;

-- Cyclic dependencies found

create operator < (procedure = halfvec_lt, leftarg = halfvec, rightarg = halfvec, commutator = >, negator = >=, join = scalarltjoinsel, restrict = scalarltsel);

alter operator <(halfvec, halfvec) owner to postgres;

-- Cyclic dependencies found

create operator > (procedure = halfvec_gt, leftarg = halfvec, rightarg = halfvec, commutator = <, negator = <=, join = scalargtjoinsel, restrict = scalargtsel);

alter operator >(halfvec, halfvec) owner to postgres;

-- Cyclic dependencies found

create operator <= (procedure = halfvec_le, leftarg = halfvec, rightarg = halfvec, commutator = >=, negator = >, join = scalarlejoinsel, restrict = scalarlesel);

alter operator <=(halfvec, halfvec) owner to postgres;

create operator >= (procedure = halfvec_ge, leftarg = halfvec, rightarg = halfvec, commutator = <=, negator = <, join = scalargejoinsel, restrict = scalargesel);

alter operator >=(halfvec, halfvec) owner to postgres;

-- Cyclic dependencies found

create operator < (procedure = sparsevec_lt, leftarg = sparsevec, rightarg = sparsevec, commutator = >, negator = >=, join = scalarltjoinsel, restrict = scalarltsel);

alter operator <(sparsevec, sparsevec) owner to postgres;

-- Cyclic dependencies found

create operator > (procedure = sparsevec_gt, leftarg = sparsevec, rightarg = sparsevec, commutator = <, negator = <=, join = scalargtjoinsel, restrict = scalargtsel);

alter operator >(sparsevec, sparsevec) owner to postgres;

-- Cyclic dependencies found

create operator <= (procedure = sparsevec_le, leftarg = sparsevec, rightarg = sparsevec, commutator = >=, negator = >, join = scalarlejoinsel, restrict = scalarlesel);

alter operator <=(sparsevec, sparsevec) owner to postgres;

create operator >= (procedure = sparsevec_ge, leftarg = sparsevec, rightarg = sparsevec, commutator = <=, negator = <, join = scalargejoinsel, restrict = scalargesel);

alter operator >=(sparsevec, sparsevec) owner to postgres;

-- Cyclic dependencies found

create operator < (procedure = vector_lt, leftarg = vector, rightarg = vector, commutator = >, negator = >=, join = scalarltjoinsel, restrict = scalarltsel);

alter operator <(vector, vector) owner to postgres;

-- Cyclic dependencies found

create operator > (procedure = vector_gt, leftarg = vector, rightarg = vector, commutator = <, negator = <=, join = scalargtjoinsel, restrict = scalargtsel);

alter operator >(vector, vector) owner to postgres;

-- Cyclic dependencies found

create operator <= (procedure = vector_le, leftarg = vector, rightarg = vector, commutator = >=, negator = >, join = scalarlejoinsel, restrict = scalarlesel);

alter operator <=(vector, vector) owner to postgres;

create operator >= (procedure = vector_ge, leftarg = vector, rightarg = vector, commutator = <=, negator = <, join = scalargejoinsel, restrict = scalargesel);

alter operator >=(vector, vector) owner to postgres;

